---
title: "ANOVA"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages('effsize')
#install.packages('multcomp')

```


## 효과 크기
  - [효과크기 신뢰구간](https://www.uvm.edu/~statdhtx/methods8/Supplements/Confidence%20Intervals%20on%20Effect%20Size.pdf)
  
```{r}
y1 = rnorm(10, 165, 10)
y2 = rnorm(10, 175, 10)
dat = data.frame(height = c(y1, y2), 
                 gender = c(rep('F', 10), rep('M', 10)))
dat
table(dat$gender)
dat <- dat %>% mutate(gender = factor(gender))
skimr::skim(dat)

library(effsize)

cohen.d(dat$height, dat$gender, pooled=FALSE)
cohen.d(dat$height, dat$gender, pooled=TRUE)
```


## 검정력에 영향을 미치는 요인들

1. 1종 오류률(유의 수준)
2. 영가설의 모평균과 실제 모평균의 차이
3. 모분산
4. 표본 크기
5. 검증 방식(일방/양방 등)

영가설(통제 집단)의 모평균과 실제 모평균의 차이에 모(통제집단)표준편차를 나누면 **효과크기**가 된다.

```{r}
library(pwr) # install.packages('pwr')
pwr.t.test(n=25, d=0.75, sig.level=.05, alternative="two.sided")
pwr.t.test(d = 0.75, sig.level=.05, alternative="two.sided", power = 0.8)
pwr.t.test(d = 0.3, sig.level=.05, alternative="two.sided", power = 0.8)
pwr.t.test(d = 1.5, sig.level=.05, alternative="two.sided", power = 0.8)
# alternative = c('two.sided', 'less', 'greater')
# type = c('two.sample', 'one.sample', 'paired')
```

* [검증력 계산 소프트웨어: GPower](https://www.psychologie.hhu.de/arbeitsgruppen/allgemeine-psychologie-und-arbeitspsychologie/gpower.html)

* [Power Analysis](https://www.statmethods.net/stats/power.html)

----

# 분산 분석

## 일요인 분산 분석

### Data 

```{r}
library(dplyr)
library(ggplot2)

dat <- read.table('https://www.uvm.edu/~statdhtx/methods8/DataFiles/Tab13-2.dat', 
           header=TRUE)
dat = dat %>% mutate(Age = ifelse(Age == 1, "Young", "Old"),
                     Condition = factor(Condition))

table(dat$Condition)

library(ggbeeswarm)
dat %>%
  ggplot(aes(Condition, Recall)) +
  geom_beeswarm(col='grey60', alpha=0.7) + 
  stat_summary(geom="pointrange", fun.data = mean_cl_normal) +
  ylab("Recall (95% CI)") +
  xlab("")

library(ggbeeswarm)
dat %>%
  ggplot(aes(Condition, Recall)) +
  geom_jitter(col='grey60', alpha=0.7, width=0.1) + 
  stat_summary(geom="pointrange", fun.data = mean_cl_normal) +
  ylab("Recall (95% CI)") +
  xlab("")
```

* 다중 비교(Multiple Comparison)의 문제점 
  * 다중성(multiplicity) 문제 : 검정의 갯수가 늘어남에 따라 계통적 오류율 증가
  
```{r}
t.test(dat %>% filter(Condition == 1) %>% pull(Recall),
       dat %>% filter(Condition == 2) %>% pull(Recall)) # var.equal = FALSE
t.test(dat %>% filter(Condition == 1) %>% pull(Recall),
       dat %>% filter(Condition == 3) %>% pull(Recall))
t.test(dat %>% filter(Condition == 1) %>% pull(Recall),
       dat %>% filter(Condition == 4) %>% pull(Recall))
# ...
t.test(dat %>% filter(Condition == 4) %>% pull(Recall),
       dat %>% filter(Condition == 5) %>% pull(Recall))

with(dat, pairwise.t.test(Recall, Condition, p.adj = "none", pool.sd = FALSE))
```  
  
* 여러 모평균에 대한 영가설 검정 방법
  * [F-분포](https://en.wikipedia.org/wiki/F-distribution)
  * F-검정의 두 자유도 $d_1$ , $d_2$
    * $d_1$ : 집단 평균 분산 추정에서 자유도
    * $d_2$ : 집단 내 공통 분산 추정에서 자유도
    
```{r}
fit <- aov(Recall ~ Condition, data = dat) # Analysis Of Variance
summary(fit)
plot(fit)
```

* 사후비교(Post-hoc comparison) 또는 다중 비교
  * 오류율
    * 약한 계통적 오류(weak familywise error) : 부분 영가설이 모두 참일 때, 그 중 하나라도 기각하는 확률. 분산분석에서 통제하는 것은 **약한 계통적 오류율**이다.
    * 강한 계통적 오류율(strong familywise error rate) : 전체 영가설을 구성하는 모든 부분 영가설의 집합에 대한 오류. 전체 영가설이 거짓일 떄, 전체 영가설을 구성하는 일부 부분 영가설 중 거짓이 영가설들로 새로운 전체 영가설을 구성했을 때 새로운 전체 영가설을 기각하는 확률
      
  * 사후 비교 방법
    * 피셔의 통제된 최소유의차이법(Protected Least Significant Difference; Protected LSD) : ANOVA에서 유의미하다면 동일한 유의수준으로 pairwise t-검정. ANOVA에서 유의미하지 않다면 t-검정을 실시하지 않는다. 약한 계통적 오류율은 통제되지만, **강한 계통적 오류율**은 통제하지 못한다.
    * 본페르니(Bonferroni) 방법 : 실제 오류율의 최대값이 유의 수준이 된다. 실제 오류율은 유의 수준보다 작으므로 **보수적**인 방법
    * 시닥(Sidak)의 방법 : 검정이 모두 독립일 때, 실제 오류율과 유의 수준이 같다.
    * 홈(Holm)의 방법: Sequential한 방법. 강한 계통적 오류율을 통제하므로, Bonferroni 방법보다 검정력이 높다.
    * 튜키(Tukey)의 방법 : 모집단이 정규분포를 만족하는 경우 쌍별 비교에 사용할 수 있다. 
      * 스튜던트화 범위 분포 
  * 오류율 사이의 관계
    * 약한 계통적 오류율 <= 거짓 발견율의 기댓값 <= 강한 계통적 오류율
    * 거짓 발견율(FDR; **F**alse **D**iscovery **R**ate)
    
```{r}
with(dat, pairwise.t.test(Recall, Condition, p.adj = "bonferroni", pool.sd = FALSE))
with(dat, pairwise.t.test(Recall, Condition, p.adj = "holm", pool.sd = FALSE))
with(dat, pairwise.t.test(Recall, Condition, p.adj = "fdr", pool.sd = FALSE))

pmat_bonf <- with(dat, pairwise.t.test(Recall, Condition, p.adj = "bonferroni", pool.sd = FALSE))
pmat_holm <- with(dat, pairwise.t.test(Recall, Condition, p.adj = "holm", pool.sd = FALSE))
pmat_fdr <- with(dat, pairwise.t.test(Recall, Condition, p.adj = "fdr", pool.sd = FALSE))

pmat_bonf$p.value - pmat_holm$p.value
pmat_holm$p.value - pmat_fdr$p.value
```

    
```{r}
(tukey <- TukeyHSD(fit))
plot(tukey)
```
    
```{r}
library(multcomp)
#fit <- aov(Recall ~ Condition, dat)
fit.tukey <- glht(fit, linfct = mcp(Condition = 'Tukey'))
summary(fit.tukey)
confint(fit.tukey)
plot(confint(fit.tukey))
#fit2 <- lm(Recall ~ Condition, dat)
#plot(confint(glht(fit2, linfct = mcp(Condition = 'Tukey'))))
```
    
    
### 대비

* 예

$$\mu_1 + \mu_2 + \mu_3 = \mu_4 + \mu_5$$
$$\mu_1 + \mu_3 = \mu_5$$



```{r}
confint(glht(fit, 
             linfct = mcp(Condition = c("`1` + `2` + `3` - `4` - `5` = 0",
                                        "`1` + `3` - `5` = 0"))))
```

$$\frac{\mu_1 + \mu_2}{2} = \frac{\mu_3 + \mu_4 + \mu_5}{3}$$
$$\frac{\mu_1 + \mu_3 + \mu_5}{3} = \frac{\mu_2 + \mu_4}{2}$$

```{r}
contr <- rbind("2 by 3" = c(-1/2, -1/2, 1/3, 1/3, 1/3),
               "odd by even" = c(-1/3, 1/2, -1/3, 1/2, -1/3))                                 
               
confint(glht(fit, linfct = mcp(Condition = contr))) 

```
    
    
* 분산분석 F-검정과 다중비교 t-검정 비교
* 단측 검정과 양측 검정 비교

## 이요인 분산 분석

### 데이터 시각화

```{r}

dat %>%
  ggplot(aes(Condition, Recall, col=Age, group=Age)) +
  geom_jitter(alpha=0.6, width=0.1) + 
  stat_summary(geom="pointrange", fun.data = mean_cl_normal) +
  ylab("Recall") +
  xlab("Condition")

library(gghighlight)
dat$null = ""
dat %>%
  ggplot(aes(Condition, Recall, col=Age, group=Age)) +
  geom_beeswarm(alpha=0.6, width=0.1) + 
  stat_summary(geom="pointrange", fun.data = mean_cl_normal) +
  facet_grid(Age ~ .) + 
  gghighlight(label_key=null) + 
  ylab("Recall") +
  xlab("Condition")

dat %>%
  ggplot(aes(Condition, Recall, col=Age, group=Age)) +
  #geom_beeswarm(alpha=0.6, width=0.1) + 
  stat_summary(geom="pointrange", fun.data = mean_cl_normal) +
  facet_grid(Age ~ .) + 
  gghighlight(label_key=null) + 
  ylab("Recall") +
  xlab("Condition")

dat %>%
  ggplot(aes(Condition, Recall, col=Age, group=Age)) +
  #geom_beeswarm(alpha=0.6, width=0.1) + 
  stat_summary(geom="pointrange", fun.data = mean_cl_normal,
               position = position_dodge(width=0.1)) + 
  #facet_grid(Age ~ .) + 
  #gghighlight(label_key=null) + 
  ylab("Recall") +
  xlab("Condition")

dat %>%
  ggplot(aes(Age, Recall, col=Age, group=Age)) +
  stat_summary(geom="pointrange", fun.data = mean_cl_normal,
               position = position_dodge(width=0.1),
               color = 'black') + 
  geom_beeswarm(alpha=0.5, width=0.1) + 
  facet_grid(. ~ Condition) + 
  #gghighlight(label_key=null) + 
  ylab("Recall") +
  xlab("Condition")
```


* 이요인 분산 분석의 영가설
  * 이요인 분산 분석의 모형
  
$$\mu_{ij} = \mu + \alpha_{i} + \beta_{j}\ \ \ \ \  \textrm{주효과 모형}$$  
$$y_{ijk} = \mu + \alpha_{i} + \beta_{j} + e_{ijk}\ \ \ \ \  \textrm{주효과 모형}$$

$$\mu_{ij} = \mu + \alpha_{i} + \beta_{j} + (\alpha\beta)_{ij} \ \ \ \ \  \textrm{상호작용 모형}$$
$$y_{ijk} = \mu + \alpha_{i} + \beta_{j} + (\alpha\beta)_{ij} + e_{ijk}\ \ \ \ \  \textrm{상호작용 모형}$$

  * 주효과, 상호작용 효과에 대한 영가설

$$ \textrm{H}_0\ : \ \alpha_i = 0 $$

$$ \textrm{H}_0\ : \ \beta_j = 0 $$

$$ \textrm{H}_0\ : \ (\alpha\beta)_{ij} = 0 $$

```{r}
fit_main <- aov(Recall ~ Condition + Age, data = dat)
summary(fit_main)

#fit_interaction <- aov(Recall ~ Condition * Age, data = dat)
fit_interaction <- aov(Recall ~ Condition + Age + Condition:Age, data = dat)
summary(fit_interaction)
```

* 주효과 모형과 상호작용 모형 비교

```{r}
library(emmeans)
# means and marginal means based on the model
emmip(ref_grid(fit_main), Age ~ Condition)  # group ~ x
emmip(ref_grid(fit_interaction), Age ~ Condition)  # group ~ x
```

## 상호작용 효과 그림(interaction plot)

```{r}
dat %>% group_by(Age, Condition) %>%
  summarise_all(mean) %>%
  ggplot(aes(x =Condition, y= Recall, col=Age, group=Age)) +
  #geom_beeswarm(col='grey60', alpha=0.7) + 
  #stat_summary(geom="point", fun.data = mean_cl_normal) +
  geom_point() + 
  geom_line() +
  ylab("Recall") +
  xlab("")
```

### Post-hoc comparison

```{r}
emmeans(fit_main, pairwise ~ Condition)
emmeans(fit_main, pairwise ~ Age)
emmeans(fit_interaction, pairwise ~ Condition)
emmeans(fit_interaction, pairwise ~ Age)
emmeans(fit_interaction, pairwise ~ Condition + Age)
```

* [참고 자료](https://cran.r-project.org/web/packages/emmeans/vignettes/FAQs.html)

---

### `emmeans` 패키지

```{r}
dat.rg <- ref_grid(fit_interaction)
plot(dat.rg)
```

```{r}
emmip(fit_interaction, ~ Age | Condition, CIs = TRUE) +
    geom_point(aes(x = Age, y = Recall), data = dat, pch = 2, color = "blue")

emmip(fit_interaction, ~ Condition | Age, CIs = TRUE) +
    geom_point(aes(x = Condition, y = Recall), data = dat, pch = 2, color = "blue")
```


----

### 참고 자료
* [Effect size and power](http://daniellakens.blogspot.com/2020/03/effect-sizes-and-power-for-interactions.html)
* [Confidence Intervals on Effect Size](https://www.uvm.edu/~statdhtx/methods8/Supplements/Confidence%20Intervals%20on%20Effect%20Size.pdf)
* [What's family in familywise error?](http://daniellakens.blogspot.com/2020/03/whats-family-in-family-wise-error.html)
* https://stat.ethz.ch/~meier/teaching/anova/contrasts-and-multiple-testing.html
* [OSF](https://osf.io/rmn8p/download)
