---
title: "Mixed Effects model"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 간단한 예

사람들의 키를 측정하여, 모집단의 키 평균을 추정하고자 한다. 이때 키 측정에 다소 큰 오차가 발생한다고 해보자.

그래서 최종 측정치는 $y_i = \mu + u_i + e_i$ 으로 나타낼 수 있다. $\mu$ 는 모집단의 키 평균이며, $u_i$ 는 사람 $i$ 의 키(모집단 키와의 편차), 그리고 $e_i$ 는 키 측정에서 발생하는 오차를 나타낸다. 

이때 $u_i$ 와 $e_i$ 가 모두 정규분포를 띈다고 가정하면 다음과 같이 키 측정값에 대한 모형을 상정할 수 있다.

$$y_i = \mu + u_i + e_i$$
$$u_i \sim \mathcal{N}(0, \sigma_u^2)$$
$$e_i \sim \mathcal{N}(0, \sigma_e^2)$$

키 측정값에 오차가 있기 때문에 한 사람에 대한 키를 여러 번 측정할 수 있다. 이때 각 측정값에서 오차가 서로 독립이라면 다음과 같은 모형을 세울 수 있다. 

$$y_{ij} = \mu + u_i + e_{ij}$$
$$1 \le j \le m(i)$$
$$u_i \sim \mathcal{N}(0, \sigma_u^2)$$

$$e_{ij} \sim \mathcal{N}(\vec{0}, \sigma_e^2\mathbb{I}_{m(i)})$$
이제 $i$ -번째 사람의 측정 횟수는 $m(i)$ 이다. $m(i)$ 는 1일수도 있고, 1보다 클 수도 있다. $j$ 는 $i$ -번째 사람의 측정 순번을 나타낸다. $y_{11}$ 은 첫 번째 사람의 첫 번째 측정값, $y_{12}$ 는 첫 번째 사람의 두 번째 측정값을 나타낸다. 이렇게 사람마다 측정횟수가 다를 수 있기 때문에 $i$ -번째 사람의 측정 횟수를 $m(i)$ 로 나타내는 것이다. 만약 첫 번째 사람의 측정횟수가 3이라면, $m(1)=3$ 이고, $1 \le j \le m(i)$ 에 따라 $y_{11}$ , $y_{12}$ , $y_{13}$ 이 가능하다.

$e_{ij} \sim \mathcal{N}(\vec{0}, \sigma_e^2\mathbb{I}_{m(i)})$ 은 $i$ 가 주어졌을 때, $e_{ij}$ 의 분포를 나타낸다. 위에서와 같이 만약 $m(1)=3$ 이고, $y_{11}$ , $y_{12}$ , $y_{13}$ 이 가능하다면, 마찬가지고 $e_{11}$ , $e_{12}$, $e_{13}$ 이 존재하고, 이들의 분산-공분산은 $\sigma_e^2\mathbb{I}_{m(i)}$ 이다.

$\sigma_e^2$ 은 $i$ 나 $j$ 에 따라 변하지 않는 값이고, $\mathbb{I}_{m(i)}$ 은 행의 수가 $m(i)$ 인 항등행렬을 나타내므로,  $\sigma_e^2\mathbb{I}_{m(i)}$ 는 대각원소가 모두 $\sigma_e^2$ 인 정방행렬을 나타낸다. 다시 말해 $e_{11}$ , $e_{12}$ , $e_{13}$ 은 분산이 같고, 공분산은 0이다. 그리고 일반적으로 $e_{ij}$ 는 $i$ 가 주어졌을 때, 분산은 동일하고, 공분산은 0인 경우이다(독립이기 때문에 공분산은 0이 된다).

### 실제 예

예를 들어서 모집단에서 키의 분포가 $\mathcal{N}(170, 15^2)$ 이고 오차의 분포가 $\mathcal{N}(0, 10^2)$ 인 경우를 생각해보자.

측정값의 분포는 $\mathcal{N}(170+0, 15^2+10^2)$ 가 된다( $\mathcal{N}(170, 18.03^2)$ ).

만약 모든 사람이 단 한 번 측정을 하여 모집단을 추정한다면, 표본 평균을 사용하면 된다. 오차가 있어서 신뢰구간이 넓어지긴 하겠지만, 전체적인 추정 방법은 변하지 않는다.



반면에 한 사람에 대해 3번 측정을 하는 경우를 생각해보자.

만약 측정하는 사람의 명수를 동일하게 유지한다면, 우리는 사람들의 키를 좀 더 정확하게 측정하여, 모집단의 키 평균을 좀 더 정확하게 추정할 수 있게 된다.

하지만 **동일한 측정 회수**의 독립 표본(한 사람 당 단 한 번의 측정)과 비교해보면 어떨까?

모평균을 다음과 같이 각 개인의 측정값을 평균한 후, 다시 전체 평균을 구한다고 할 때, 이는 전체 표본 평균을 구하는 것과 동일하다.

$$\{(y_{11} + y_{12} + y_{13})/3 + (y_{21} + y_{22} + y_{23})/3 + \cdots + (y_{n1} + y_{n2} + y_{n3})/3\}/n $$
$$ = (y_{11} + y_{12} + y_{13} + y_{21} + y_{22} + \cdots + y_{n1} + y_{n2} + y_{n3})/(3n) = \bar{y}$$ 

이때 전체 표본 평균의 평균과 분산을 구해보면 다음과 같다.

$$\mathbb{E} [\sum{y_{ij}}/3n] = (3n \cdot \mu) / 3n = \mu$$
$$\mathbb{V} [\sum{y_{ij}}/3n] = [\mathbb{V}[y_{11}]+\mathbb{V}[y_{12}] +  2\mathbb{C}[y_{11}, y_{12}] + \cdots] 
]/{(3n)^2}$$

여기서 $\mathbb{C}[y_{1j}, y_{2k}] = 0$ 이지만, $\mathbb{C}[y_{1j}, y_{1k}] = \mathbb{V}[u]$ 이다(아래 전개 참조).

$$\mathbb{C}[y_{11}, y_{12}] = \mathbb{C}[u_1 + e_{11} , u_1 + e_{12}] = \mathbb{C}[u_1, u_1] + \mathbb{C}[u_1, e_{12}] + \mathbb{C}[u_1, e_{11}] + \mathbb{C}[e_{11}, e_{12}] = \mathbb{V}[u_1] = \mathbb{V}[u]$$

따라서 $\mathbb{V} [\sum{y_{ij}}/3n]$ 은 다음과 같이 구한다.

$$\mathbb{V} [\sum{y_{ij}}/3n] = \left[\sum_{i}\sum_{j}\mathbb{V}[y_{ij}]+\sum_{i}\sum_{j}\sum_{k}\mathbb{C}[y_{ij}, y_{ik}] \right]/{(3n)^2}$$

$$\mathbb{V} [\sum{y_{ij}}/3n] =\left[ 3n \cdot\mathbb{V}[y_{ij}]+2\cdot3n\cdot\mathbb{V}[u]  \right]/{(3n)^2}$$
$$\mathbb{V} [\sum{y_{ij}}/3n] =\left[\mathbb{V}[y_{ij}]+2\mathbb{V}[u_i]  \right]/(3n)$$

$$\mathbb{V} [\sum{y_{ij}}/3n] =\left[\mathbb{V}[u]+\mathbb{V}[e]+2\mathbb{V}[u] \right]/(3n)$$

결론적으로 전체 표본 평균의 분산은 반복 측정의 경우에 독립 표본의 경우보다 커짐을 확인할 수 있고, 이에 따라 반복 측정 결과를 독립 표본일 때와 같이 영가설 검정을 실시한다면 1종 오류율이 증가할 것임을 예상할 수 있다.













